version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"


  db:
    image: postgres:12.0
    volumes:
      - postgres_data_tg:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
    ports:
      - "5432:5432"

volumes:
  postgres_data_tg: